### PR TITLE
to_string() optimization: using deque instead of list

### PR DESCRIPTION
**Pull request by marc1n**
It is easy and probably significant optimization of HTML elements serialization.

### CODE REVIEW

**Comment by marc1n** [comment]
Tests (runned by py.test):
 - before optimization: 59 passed in 0.36 second
 - after optimization: 59 passed in 0.14 seconds

**Comment by lfaraone** [comment]
Thanks for the PR @marc1n ! Can you fill out the [Dropbox CLA](https://opensource.dropbox.com/cla/)?

**Comment by marc1n** [comment]
CLA filled.

**Comment by benjaminp** [comment]
Why would this be faster? Do you have an benchmarks demonstrating that it is?

**Comment by marc1n** [comment]
No, I don't have any benchmarks but the change is simple and in theory it must be some gain in performance since deque is optimized for append operation (it doesn't use realloc()).

**Comment by benjaminp** [comment]
Some benchmark should have been a prerequisite for merging this--
particularly since it should be easy to capture in a micro benchmark.

**Pull request merged**
